version: "3.5"

services:
  webserver:
    build:
      context: .
      dockerfile: dockerfiles/php-a2.dockerfile
    container_name: webserver_container_name
    restart: "always"
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/docker-runtime/a2-rootdir:/var/www/html
      - ~/.ssh:${DIR_SSH}:ro
      - ~/.npmrc:${PATH_NPMRC}:ro

  db:
    build:
      context: .
      dockerfile: dockerfiles/mariadb.dockerfile
    container_name: db_container_name
    network_mode: "host"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ~/docker-runtime/db-data:/var/lib/mysql

networks:
  test_network:
    name: custom_network_name