version: "3.5"

services:
  webserver:
    build:
      context: .
      dockerfile: dockerfiles/php-a2.dockerfile
      args:
        WEBSERVER_USER: ${WEBSERVER_USER}
    container_name: webserver_container_name
    restart: "always"
    # network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    # user: ${WEBSERVER_USER}
    volumes:
      - ${A2_ROOT}:/var/www/html
      - ${DIR_SSH}:/home/${WEBSERVER_USER}/.ssh:ro
      - ${PATH_NPMRC}:/home/${WEBSERVER_USER}/.npmrc:ro

  db:
    build:
      context: .
      dockerfile: dockerfiles/mariadb.dockerfile
    container_name: db_container_name
    # network_mode: "host"
    ports:
      - "3306:3306"
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ${DB_ROOT}:/var/lib/mysql

# networks:
#   test_network:
#     name: custom_network_name